K8SPSMDB-338 Remove obsolete configuration block
Percona-Lab/percona-openshift pull request #84
Opened 2020-12-11 13:12 UTC by cap1984

2020-12-11 13:18 UTC, delgod requested changes
I am sure 3.11 will not work

2020-12-11 13:19 UTC, cap1984 commented
> I am sure 3.11 will not work

it did

2020-12-14 10:00 UTC, delgod approved these changes

2020-12-14 10:09 UTC, hors approved these changes

2020-12-14 10:11 UTC, merged