Add MongoDB support into sysbench image
Percona-Lab/percona-openshift pull request #88
Opened 2021-05-11 11:41 UTC by maxkondr

2021-05-11 11:41 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/Percona-Lab/percona-openshift?pullRequest=88) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/Percona-Lab/percona-openshift?pullRequest=88) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/Percona-Lab/percona-openshift?pullRequest=88) it.</sub>

2021-05-11 15:00 UTC, delgod approved these changes

2021-05-14 06:45 UTC, EvgeniyPatlan requested changes
each PR should be associated with the Jira ticket. So Please add ticket number into commit description

2021-05-14 07:39 UTC, maxkondr commented
> each PR should be associated with the Jira ticket. So Please add ticket number into commit description

Done

2021-05-14 09:41 UTC, EvgeniyPatlan approved these changes

2021-05-14 12:00 UTC, merged